//
//  Const.h
//  WJW2
//
//  CREATED BY LUO YU ON 2017-02-13.
//  COPYRIGHT © 2017 HUAAO TECH. ALL RIGHTS RESERVED.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const KEY_AMAP;
FOUNDATION_EXPORT NSString *const KEY_XIAOYU_EXTID;

FOUNDATION_EXPORT NSString *const URL_USER_AGREEMENT;
FOUNDATION_EXPORT NSString *const URL_PRIVACY_AGREEMENT;
